import numpy as np

# A tiny char-level next-character MLP. Small enough to embed in the kernel and
# run a real forward pass on bare metal; trained here to overfit a short corpus.
np.random.seed(7)

corpus = (
    "living os is an ai native operating system. "
    "agents are first class kernel resources. "
    "you express goals and the society assembles. "
    "the kernel schedules agents and gates capabilities. "
    "memory persists. intelligence is a system resource. "
) * 12

chars = sorted(set(corpus))
V = len(chars)
stoi = {c:i for i,c in enumerate(chars)}
itos = {i:c for i,c in enumerate(chars)}

C = 4    # context length
D = 8    # embedding dim
H = 48   # hidden units

# Build training pairs
X, Y = [], []
ctx = [stoi[' ']]*C
for ch in corpus:
    X.append(list(ctx)); Y.append(stoi[ch])
    ctx = ctx[1:] + [stoi[ch]]
X = np.array(X); Y = np.array(Y)
N = len(X)

E  = np.random.randn(V, D) * 0.5
W1 = np.random.randn(C*D, H) * (1/np.sqrt(C*D))
b1 = np.zeros(H)
W2 = np.random.randn(H, V) * (1/np.sqrt(H))
b2 = np.zeros(V)

def forward(xb):
    emb = E[xb].reshape(len(xb), C*D)
    h = np.tanh(emb @ W1 + b1)
    logits = h @ W2 + b2
    return emb, h, logits

lr = 0.2
for epoch in range(4000):
    emb, h, logits = forward(X)
    logits -= logits.max(1, keepdims=True)
    p = np.exp(logits); p /= p.sum(1, keepdims=True)
    loss = -np.log(p[np.arange(N), Y] + 1e-9).mean()
    # backprop
    dlogits = p.copy(); dlogits[np.arange(N), Y] -= 1; dlogits /= N
    dW2 = h.T @ dlogits; db2 = dlogits.sum(0)
    dh = dlogits @ W2.T
    dpre = dh * (1 - h**2)
    dW1 = emb.T @ dpre; db1 = dpre.sum(0)
    demb = (dpre @ W1.T).reshape(N, C, D)
    dE = np.zeros_like(E)
    for i in range(N):
        for j in range(C):
            dE[X[i, j]] += demb[i, j]
    for arr, g in ((E,dE),(W1,dW1),(b1,db1),(W2,dW2),(b2,db2)):
        arr -= lr * g
    if epoch % 500 == 0:
        print(f"epoch {epoch} loss {loss:.3f}")

# Greedy sample check
def gen(seed, n=80):
    ctx = [stoi.get(c, stoi[' ']) for c in seed[-C:].rjust(C)]
    out = seed
    for _ in range(n):
        _,_,logits = forward(np.array([ctx]))
        nx = int(logits[0].argmax())
        out += itos[nx]; ctx = ctx[1:] + [nx]
    return out
print("SAMPLE:", gen("the "))

def arr(a):
    return ", ".join(f"{x:.5f}" for x in a.flatten())

vocab_escaped = "".join(chars).replace("\\","\\\\").replace("\"","\\\"")
with open(r"C:\Users\kodesweb3\Desktop\living os\kernel\src\nn_weights.rs","w",encoding="utf-8") as f:
    f.write("//! Embedded weights for the on-metal char-level MLP (trained offline).\n")
    f.write("//! Generated by tools/train_nn.py. Real inference runs in nn.rs.\n")
    f.write(f"pub const V: usize = {V};\npub const D: usize = {D};\n")
    f.write(f"pub const C: usize = {C};\npub const H: usize = {H};\n")
    f.write(f"pub const VOCAB: &str = \"{vocab_escaped}\";\n")
    f.write(f"pub static E: [f32; {E.size}] = [{arr(E)}];\n")
    f.write(f"pub static W1: [f32; {W1.size}] = [{arr(W1)}];\n")
    f.write(f"pub static B1: [f32; {b1.size}] = [{arr(b1)}];\n")
    f.write(f"pub static W2: [f32; {W2.size}] = [{arr(W2)}];\n")
    f.write(f"pub static B2: [f32; {b2.size}] = [{arr(b2)}];\n")
print("wrote nn_weights.rs : V=%d D=%d C=%d H=%d" % (V,D,C,H))
